# -*- coding: utf-8 -*-
"""20211007_프로그래머스 연습문제_Lv1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Nb6y5nwQAERscACdiTy7eoCKsCgCVsnK
"""

def solution(s, n):
    s = list(s)

# chr() 함수 : 아스키 코드 값을 문자로 변환해주는 함수 (10진수, 16진수 사용 가능)
# ord() 함수 : 특정한 한 문자를 아스키 코드 값으로 변환해주는 함수
    for i in range(len(s)):
        if s[i].isupper(): # s[i]번째 문자가 대문자인 경우
            s[i] = chr((ord(s[i])-ord('A') + n) % 26 + ord('A')) 
            # s[i]의 값은 (s[i]의 아스키 코드 값 - 'A'의 아스키 코드 값(65)) + n을 해주어 몇 번째에 있는 알파벳인지 찾아준다. (알파벳은 총 25글자(65~90))
            # ord(s[i])-ord('A') 26으로 나눈 나머지 값에 'A' 아스키 코드 값 = 65를 더해주면 n만큼 민 값이 나오게 된다.
            # % 26 을 해주는 이유는 :: z 또는 Z의 범위를 넘어가지 않도록 하기 위해서
        elif s[i].islower(): # s[i]번째 문자가 소문자인 경우
            s[i] = chr((ord(s[i])-ord('a') + n) % 26 + ord('a'))
            # 'a'의 아스키 코드 값(97) + n
    return ''.join(s) # join(리스트) 함수 :: 리스트의 문자열들을 합치는 역할을 한다

    # (참고한 블로그 : https://wooaoe.tistory.com/72)
    # (아스키 코드 관련 참고 : https://namu.wiki/w/%EC%95%84%EC%8A%A4%ED%82%A4%20%EC%BD%94%EB%93%9C?from=%EC%95%84%EC%8A%A4%ED%82%A4%EC%BD%94%EB%93%9C)

#################### output TEST ####################     
solution('AB', 1) # result : "BC"
solution('z', 1) # result : "a"
solution('a B z', 4) # result : "e F d"
