# -*- coding: utf-8 -*-
"""20211006_프로그래머스 연습문제_Lv1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16vicevXlO6yioiMUM4ml8PXxZbuHhaCc
"""

# 소수 찾기 문제
def solution(n):
    # 에라토스테네스의 체
    a = [False,False] + [True]*(n-1)
    answer = []

    for i in range(2,n+1):
        if a[i]:
            answer.append(i)
            for j in range(2*i, n+1, i):
                a[j] = False
    
    return len(answer)
#################### output ####################
solution(10) # result : 4
solution(5) # result : 3
