# -*- coding: utf-8 -*-
"""20210930_프로그래머스 연습문제_Lv1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uAuoxDxXVxU5GHgcWpogWolS26OQ8GH_
"""

# 약수의 합 문제
def solution(n):
    n = int(n)
    n_lists = []
    
    # 약수가 들어간 리스트를 만듬
    for i in range(1, n+1):
        if (n % i == 0):
            n_lists.append(i)
    # 그 리스트의 요소들을 int형으로 바꾸고 모두 더함        
    return sum(map(int, n_lists))

solution(12)