# -*- coding: utf-8 -*-
"""20211001_프로그래머스 연습문제_Lv1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/
"""

# 문자열 다루기 기본 문제
def solution(s):
    if (len(s) == 4 or len(s) == 6) and s.isdigit() == True:
    # isdigit은 문자를 검사하여 digit(숫자)인지를 검사해주는 메소드이다.
        return True
    
    else :
        return False
############ output ############    
solution("a234") # False
solution("1234") # True

###############################################################################################

# 2016년 문제
import datetime

def solution(a, b):
    days = ['MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN']
    answer = days[datetime.date(2016, a, b).weekday()]
    # datetime 모듈의 weekday() 함수는 날짜의 요일 정보를 숫자값으로 리턴해준다 (0(월)~6(화)까지)
    return answer
############ output ############    
solution(5, 24) # 'TUE'

###############################################################################################

# 두 정수 사이의 합 문제
def solution(a, b):
    answer = 0
    if a < b:
        for i in range(a, b+1):
            answer += i
        return answer
    
    else:
        return sum(list(range(b, a+1)))
        # ex) a=5, b=3일 경우 :: 3,4,5가 들어있는 리스트를 만들고 sum 한다.
############ output ############
solution(3, 5) # 12
solution(3, 3) # 3
solution(5, 3) # 12

###############################################################################################

# 같은 숫자는 싫어 문제
def solution(arr):
    answer = []
    for i in range(len(arr)):
        if i == 0:
            answer.append(arr[i])
        # 0번째 숫자는 무조건 정답 list에 추가    
        
        elif arr[i] != arr[i-1]:
            answer.append(arr[i])
        # 현재 arr 인덱스의 값이 바로 전 값과 다를 경우 :: 정답 list에 추가, 같을 경우 :: 추가 x    
    return answer
############ output ############
solution([1,1,3,3,0,1,1]) # [1, 3, 0, 1]
solution([4,4,4,3,3]) # [4, 3]

###############################################################################################
