# -*- coding: utf-8 -*-
"""20211001_프로그래머스 연습문제_Lv1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zzXLrCfcGmdfUMeQ_1DLtrJh2KY2Gwjd
"""

# 문자열 다루기 기본 문제
def solution(s):
    if (len(s) == 4 or len(s) == 6) and s.isdigit() == True:
    # isdigit은 문자를 검사하여 digit(숫자)인지를 검사해주는 메소드이다.
        return True
    
    else :
        return False
############ output ############    
solution("a234") # False
solution("1234") # True

####################################################################################

